In [4]:
import pandas as pd
import numpy as np
import gwaslab as gl
import logging
import matplotlib.pyplot as plt

# 设置全局日志级别变量
logging.getLogger("matplotlib").setLevel(logging.ERROR)
plt.style.use('default')

sig_level = 5e-8

array_add_path = "/LARGE0/gr10478/b37974/Pulmonary_Hypertension/cteph_agp3k/snippet_analysis/02.array_check_impute/04.array_assoc_result/cteph_agp3k.array.sex.10pc.additive.PHENO1.glm.logistic"

In [5]:
sumstats_add = gl.Sumstats(array_add_path, fmt="plink2", build='38', ea='A1', nea='OMITTED', OR_95L='L95', OR_95U='U95')

2025/12/04 05:57:42 GWASLab v3.6.0 https://cloufield.github.io/gwaslab/
2025/12/04 05:57:42 (C) 2022-2025, Yunye He, Kamatani Lab, GPL-3.0 license, gwaslab@gmail.com
2025/12/04 05:57:42 Python version: 3.9.21 | packaged by conda-forge | (main, Dec  5 2024, 13:51:40)
[GCC 13.3.0]
2025/12/04 05:57:42 Start to load format from formatbook....
2025/12/04 05:57:42  -plink2 format meta info:
2025/12/04 05:57:42   - format_name  : PLINK2 .glm.firth, .glm.logistic,.glm.linear
2025/12/04 05:57:42   - format_source  : https://www.cog-genomics.org/plink/2.0/formats
2025/12/04 05:57:42   - format_version  : Alpha 3.3 final (3 Jun)
2025/12/04 05:57:42   - last_check_date  :  20220806
2025/12/04 05:57:42  -plink2 to gwaslab format dictionary:
2025/12/04 05:57:42   - plink2 keys: ID,#CHROM,POS,REF,ALT,A1,OBS_CT,A1_FREQ,BETA,LOG(OR)_SE,SE,T_STAT,Z_STAT,P,LOG10_P,MACH_R2,OR
2025/12/04 05:57:42   - gwaslab values: SNPID,CHR,POS,REF,ALT,EA,N,EAF,BETA,SE,SE,T,Z,P,MLOG10P,INFO,OR
2025/12/04 05:57:42 Start to initialize gl.Sumstats from file :/LARGE0/gr10478/b37974/Pulmonary_Hypertension/cteph_agp3k/snippet_analysis/02.array_check_impute/04.array_assoc_result/cteph_agp3k.array.sex.10pc.additive.PHENO1.glm.logistic
2025/12/04 05:57:47  -Reading columns          : L95,ID,P,A1_FREQ,ALT,POS,#CHROM,OR,A1,REF,U95,Z_STAT,OMITTED,LOG(OR)_SE,OBS_CT
2025/12/04 05:57:47  -Renaming columns to      : OR_95L,SNPID,P,EAF,ALT,POS,CHR,OR,EA,REF,OR_95U,Z,NEA,SE,N
2025/12/04 05:57:47  -Current Dataframe shape : 4282768  x  15
2025/12/04 05:57:47  -Initiating a status column: STATUS ...
2025/12/04 05:57:47  -Genomic coordinates are based on GRCh38/hg38...
2025/12/04 05:57:47  -EA,REF and ALT columns are available: assigning NEA...
2025/12/04 05:57:47  -For variants with EA == ALT : assigning REF to NEA ...
2025/12/04 05:57:48  -For variants with EA != ALT : assigning ALT to NEA ...
2025/12/04 05:57:49 Start to reorder the columns...v3.6.0
2025/12/04 05:57:49  -Current Dataframe shape : 4282768 x 16 ; Memory usage: 414.33 MB
2025/12/04 05:57:49  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,EAF,SE,Z,P,OR,OR_95L,OR_95U,N,STATUS,REF,ALT
2025/12/04 05:57:49 Finished reordering the columns.
2025/12/04 05:57:49  -Trying to convert datatype for CHR: string -> Int64...Int64
2025/12/04 05:57:49  -Column  : SNPID  CHR   POS   EA       NEA      EAF     SE      Z       P       OR      OR_95L  OR_95U  N     STATUS   REF      ALT
2025/12/04 05:57:49  -DType   : object Int64 int64 category category float64 float64 float64 float64 float64 float64 float64 int64 category category category
2025/12/04 05:57:49  -Verified: T      T     T     T        T        T       T       T       T       T       T       T       T     T        T        T
2025/12/04 05:57:49  -Current Dataframe memory usage: 418.41 MB
2025/12/04 05:57:49 Finished loading data successfully!
2025/12/04 05:57:49 Path component detected: ['140057378967024']
2025/12/04 05:57:49 Creating path: ./140057378967024

In [ ]:
sumstats_add.plot_mqq()

In [9]:
sumstats_add.data[sumstats_add.data['SNPID'] == 'chr9:65411978:C:T']

,SNPID,CHR,POS,EA,NEA,EAF,SE,Z,P,OR,OR_95L,OR_95U,N,STATUS,REF,ALT
2456447,chr9:65411978:C:T,9,65411978,T,C,0.717121,0.122063,5.65581,1.551100e-08,1.99444,1.57008,2.5335,1688,3899999,C,T

In [3]:
sumstats_add.get_lead()

2025/12/04 05:38:19 Start to extract lead variants...v3.6.0
2025/12/04 05:38:19  -Current Dataframe shape : 4282768 x 16 ; Memory usage: 418.41 MB
2025/12/04 05:38:19  -Processing 4282768 variants...
2025/12/04 05:38:19  -Significance threshold : 5e-08
2025/12/04 05:38:19  -Sliding window size: 500  kb
2025/12/04 05:38:20  -Using P for extracting lead variants...
2025/12/04 05:38:20  -Found 3 significant variants in total...
2025/12/04 05:38:20  -Identified 3 lead variants!
2025/12/04 05:38:20 Finished extracting lead variants.

,SNPID,CHR,POS,EA,NEA,EAF,SE,Z,P,OR,OR_95L,OR_95U,N,STATUS,REF,ALT
177100,chr1:147027142:G:C,1,147027142,C,G,0.637145,0.112289,5.82132,5.838470e-09,1.92259,1.54279,2.39589,1688,3899999,G,C
2456376,chr9:60545749:A:G,9,60545749,G,A,0.715047,0.120910,5.51540,3.479850e-08,1.94813,1.53709,2.46909,1688,3899999,A,G
2456447,chr9:65411978:C:T,9,65411978,T,C,0.717121,0.122063,5.65581,1.551100e-08,1.99444,1.57008,2.53350,1688,3899999,C,T